### ISSUE TITLE
 UnboundLocalError: local variable 'model' referenced before assignment

### ISSUE THREAD

**Issue by aFrogThatExists** [zzbuzzard/pixartdiffusion#1]
When I run the command
`train data/*.png`
I get this error message. I don't know if this is a bug or just user error.

```
Traceback (most recent call last):
  File "C:\Users\samue\Downloads\pixartdiffusion-main\pixartdiffusion\train.py", line 168, in <module>
    run()
  File "C:\Users\samue\Downloads\pixartdiffusion-main\pixartdiffusion\train.py", line 68, in run
    model = model.UNet().to(device)
UnboundLocalError: local variable 'model' referenced before assignment
```

**Comment by zzbuzzard** [comment]
Hey, thanks for pointing this out! This was a bug on my end, should be fixed now.

I ran it locally just now to check everything was working with these exact commands:

`train.py ../data/*.png -save_path ../models/test.pt -load_path ../models/test.pt`
then
`sample.py ../models/test.pt 16 -o out.png -noise_mul 8`

Though I should advise you that training takes quite a long time and needs quite a lot of data - the model in the repo was trained for 12,000 epochs (this took many hours on google colab free tier, haha) on a dataset of ~2000 images.

Sorry for the messy code btw! This project started as a notebook and was ported to this form fairly messily.

**Comment by aFrogThatExists** [comment]
Thanks for the help! =D
